//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ride_detail
    {
        public int id { get; set; }
        public int passengerID { get; set; }
        public int driverID { get; set; }
        public string from_destination { get; set; }
        public string to_destination { get; set; }
        public double from_lat { get; set; }
        public double from_lng { get; set; }
        public double to_lat { get; set; }
        public double to_lng { get; set; }
        public Nullable<System.DateTime> reserve_date_start { get; set; }
        public Nullable<System.DateTime> reserve_date_end { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> total_miles { get; set; }
        public Nullable<double> amount { get; set; }
        public int status { get; set; }
        public string review { get; set; }
        public Nullable<double> rating { get; set; }
    }
}
