//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int id { get; set; }
        public string name { get; set; }
        public string model_name { get; set; }
        public string manufacturer_name { get; set; }
        public Nullable<int> year_name { get; set; }
        public Nullable<int> ownerId { get; set; }
    
        public virtual user user { get; set; }
    }
}
