//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.vehicles = new HashSet<vehicle>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string nic { get; set; }
        public string userType { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lng { get; set; }
        public Nullable<int> is_login { get; set; }
        public Nullable<int> is_vehicle_added { get; set; }
        public string reg_id { get; set; }
        public Nullable<int> is_available { get; set; }
        public Nullable<double> current_lat { get; set; }
        public Nullable<double> current_lgn { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<vehicle> vehicles { get; set; }
    }
}
